# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80056c9642cf054973d1296d1bf47933ac4cfc22af425a38f2fb6ba3315a3c2047a3ad7f73a7e2cba255f7ae00c649ddddb328a383ca64571c601ef4c4e03075

test:
  secret_key_base: 8ed098bf5b4ece370ab829ef1fa94300bc68c96b41ff805dc908b0526c60ff7c73ad56a5c193f8636f8d29284dcb7ea0f73334cdc1a2fdea71d8f43a19554ab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
